on: [push, pull_request]

name: air.yaml

permissions: read-all

jobs:
  air:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Check formatting
        run: air format . --check
